name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Copy libraries
      run: |
        mkdir -p ~/.m2/repository/com/example/jasypt/1.9.2
        cp libs/jasypt-1.9.2.jar ~/.m2/repository/com/example/jasypt/1.9.2/jasypt-1.9.2.jar

    - name: Current Path(cli exmaple1)
      run: echo $PATH

    - name: Current Path(cli exmaple2)
      run: |
        echo $PATH

    - name: Build with Maven
      run: mvn -B clean install -f pom.xml
