name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
  MAVEN_OPTS: -Xmx2048m
  mode: prod

jobs:
  build:
    runs-on: ubuntu-latest

    # 특정 커밋 체크아웃
  # - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

    # v3(Node 16, deprecated) -> v4(Node 20)
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 모든 히스토리를 가져오기 위해 필요

    # test - dev
    # - name: Set up JDK 17
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '17'
    #     distribution: 'adopt'

    # java Supported distributions: https://github.com/actions/setup-java?tab=readme-ov-file
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'oracle'

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    # - name: Copy libraries - dev mode
    #   run: |
    #     mkdir -p ~/.m2/repository/com/example/jasypt/1.9.2
    #     cp libs-${{ env.mode }}/jasypt-1.9.2.jar ~/.m2/repository/com/example/jasypt/1.9.2/jasypt-1.9.2.jar

    - name: Copy libraries1 - prod mode
      run: |
        echo "Current Path1: $PWD"
        ls -lart
        mkdir -p ~/.m2/repository/com/example/jasypt/1.9.2
        cp libs/jasypt-1.9.2.jar ~/.m2/repository/com/example/jasypt/1.9.2/jasypt-1.9.2.jar
        mkdir -p ~/.m2/repository/com/example/jasypt-spring31/1.9.2
        cp libs-prod/jasypt-spring31-1.9.2.jar ~/.m2/repository/com/example/jasypt-spring31/1.9.2/jasypt-spring31-1.9.2.jar
        
    
    # - name: Copy libraries2 - prod mode
    #   run: |
    #     echo "Current Path2: $PWD"
    #     ls -lart libs-${{ env.mode }}
    #     mkdir -p ~/.m2/repository/com/example/jasypt-spring31/1.9.2
    #     cp libs-prod/jasypt-spring31-1.9.2.jar ~/.m2/repository/com/example/jasypt-spring31/1.9.2/jasypt-spring31-1.9.2.jar
    #     ls -lart ~/.m2/repository/com/example/jasypt-spring31/1.9.2/

    - name: Set custom Maven options
      run: echo "MAVEN_OPTS=-Dmaven.test.skip=true" >> $GITHUB_ENV

    - name: Current Path(cli exmaple1)
      run: echo $PATH

    - name: Current Path(cli exmaple2)
      run: |
        echo $PATH

    - name: Build with Maven
      # run: mvn -B clean install -Pprod -f pom.xml
      # stack trace, -e
      run: mvn -e clean install -Pprod -f pom.xml

    - name: Print environment variables
      run: |
        echo "JAVA_HOME: ${{ env.JAVA_HOME }}"
        echo "MAVEN_OPTS: ${{ env.MAVEN_OPTS }}"
        echo "mode: ${{ env.mode }}"
        
    - name: Get the last commit message
      id: commit-message
      run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

    - name: Create and push tag
      run: |
        COMMIT_MSG="${{ steps.commit-message.outputs.message }}"
        TAG_NAME=$(echo "$COMMIT_MSG" | head -n 1 | sed 's/ /_/g')
        git tag "$TAG_NAME"
        git push origin "$TAG_NAME"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
