name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # 특정 커밋 체크아웃
  # - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

    # v3(Node 16, deprecated) -> v4(Node 20)
    steps:
    - uses: actions/checkout@v4

    # test - dev
    # - name: Set up JDK 17
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '17'
    #     distribution: 'adopt'

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'adopt'

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Copy libraries - dev mode
      run: |
        mkdir -p ~/.m2/repository/com/example/jasypt/1.9.2
        cp libs/jasypt-1.9.2.jar ~/.m2/repository/com/example/jasypt/1.9.2/jasypt-1.9.2.jar

    - name: Current Path(cli exmaple1)
      run: echo $PATH

    - name: Current Path(cli exmaple2)
      run: |
        echo $PATH

    - name: Build with Maven
      run: mvn -B clean install -Pprod -f pom.xml
